server:
  port: 8080 #端口号
spring:
  application:
    name: gateway #微服务名称
  cloud:
    nacos:
      server-addr: 192.168.80.129:8848 #nacos服务注册中心地址
    gateway: #网关
      default-filters: #使用自定义网关过滤器 GatewayFilter
        - name: PrintPram
          args:
            name: 1
            age: 2
            sex: 3
        - name: PrintInfo
        #- PrintInfo # 在所有路由添加自定义过滤器，打印请求信息
      routes: #路由配置
        - id: user #路由规则ID，唯一 用户微服务
          uri: lb://user-service #路由目标服务和nacos中的服务名称一致，lb代表负载均衡，会从注册中心获取服务列表
          predicates: #路由断言，判断是否符合规则，符合规则才能路由到目标服务
            - Path=/users/**,/addresses/** #path 以请求路径作为判断规则，路径必须包含users
            #- Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2037-01-21T17:42:47.789-07:00[America/Denver] #两个时间点之间的请求，指定只能在某时段访问该服务
            #- Cookie=chocolate, ch.p #请求必须包含某些cookie 多个用逗号隔开
            #- Header=X-Request-Id, \d+ #请求必须包含某些header
            #- Host=**.somehost.org,**.anotherhost.org #请求必须是访问某个域名
            #- Method=GET, POST #请求必须是指定的方式
            #- Query=name, class #请求必须包含指定参数
            #- After=2017-01-20T17:42:47.789-07:00[America/Denver] #请求时间必须晚于指定时间
            #- RemoteAddr=192.168.0.1/24,192.168.0.2/24 #请求者的IP必须是指定范围
            #- weight=1,2 #权重处理
        - id: order # 订单微服务
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters: #过滤器 自定义网关过滤器 GatewayFilter
            - name: PrintInfo #
        - id: pay # 支付微服务
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: cart # 购物车微服务
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: item # 商品微服务
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
#密钥
hm:
  jwt:
    location: classpath:hmall.jks #密钥文件
    alias: hmall #密钥别名
    password: hmall123 #密钥密码
    tokenTTL: 30m #token有效期
  auth:
    excludePaths: #认证排除路径
      - /search/**
      - /users/login
      - /items/**
      - /hi
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123