server:
  port: 8082
  tomcat:
    threads:
      max: 50 #最大线程数
    accept-count: 50 #最大排队等待数
    max-connections: 100 #允许的最大连接数 默认是8192
feign:
  okhttp:
    enabled: true #开启okhttp功能
  sentinel:
    enabled: true #开启sentinel功能
hm:
  swagger:
    title: 购物车服务接口文档
    package: com.wave.cart.controller
  db:
    database: hm-cart
  mq:
    virtual: hmall
    name: hmall
    pwd: 123